webkitMediaStream:MediaStream()
webkitRTCPeerConnection:RTCPeerConnection()
webkitSpeechGrammar:SpeechGrammar()
webkitSpeechGrammarList:SpeechGrammarList()
webkitSpeechRecognition:SpeechRecognition()
webkitSpeechRecognitionError:SpeechRecognitionError()
webkitSpeechRecognitionEvent:SpeechRecognitionEvent()
webkitURL:URL()

WebKitAnimationEvent:AnimationEvent()
WebKitCSSMatrix:DOMMatrix()
WebKitMutationObserver:MutationObserver()
WebKitTransitionEvent:TransitionEvent()

webkitCancelAnimationFrame:webkitCancelAnimationFrame()
webkitRequestAnimationFrame:webkitRequestAnimationFrame()
webkitRequestFileSystem:webkitRequestFileSystem()
webkitResolveLocalFileSystemURL:webkitResolveLocalFileSystemURL()
webkitStorageInfo:DeprecatedStorageInfo

onwebkitanimationend:null
onwebkitanimationiteration:null
onwebkitanimationstart:null
onwebkittransitionend:null